# Generated by Django 4.2.1 on 2023-05-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_home_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home_banner',
            name='text6',
        ),
    ]
