# Generated by Django 4.2.1 on 2023-05-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Collection image')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('item_col', models.CharField(max_length=60, verbose_name='Item collection')),
                ('item_count', models.CharField(max_length=60, verbose_name='Item count')),
                ('category', models.CharField(max_length=60, verbose_name='Category')),
                ('category_name', models.CharField(max_length=60, verbose_name='Category name')),
                ('btn_name', models.CharField(max_length=40, verbose_name='Collection Button Name')),
            ],
        ),
    ]
