# Generated by Django 4.2.1 on 2023-05-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeNFT_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('text1', models.CharField(max_length=256, verbose_name='text1')),
                ('text_linked', models.CharField(blank=True, max_length=256, verbose_name='Linked text')),
                ('text3', models.CharField(blank=True, max_length=256, verbose_name='text3')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
            ],
        ),
    ]
