# Generated by Django 4.2.1 on 2023-05-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_homenft_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.BooleanField(verbose_name='msc/dig/blc/vtr')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
                ('img_auth', models.ImageField(upload_to='images', verbose_name='Author image')),
                ('title', models.CharField(max_length=60, verbose_name='Title')),
                ('text1', models.CharField(max_length=256, verbose_name='text1')),
                ('text_linked', models.CharField(blank=True, max_length=256, verbose_name='Linked text')),
                ('text3', models.CharField(blank=True, max_length=256, verbose_name='text3')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('bid', models.CharField(max_length=60, verbose_name='Curent Bid')),
                ('bid_value', models.CharField(max_length=60, verbose_name='Bid value')),
                ('bid_price', models.CharField(max_length=60, verbose_name='Bid price (USD)')),
                ('bid_ends', models.CharField(max_length=60, verbose_name='Ends In')),
                ('end_date', models.CharField(max_length=60, verbose_name='Ends date')),
                ('end_time', models.CharField(max_length=60, verbose_name='Ends time')),
                ('btn_name', models.CharField(max_length=40, verbose_name='Item Button Name')),
            ],
        ),
    ]
