# Generated by Django 4.2.1 on 2023-05-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_item_market'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_market',
            name='text3',
        ),
        migrations.AlterField(
            model_name='item_market',
            name='category',
            field=models.CharField(max_length=60, verbose_name='Category filter'),
        ),
    ]
